### PR TITLE
Add information about hstore to README

### PR DESCRIPTION
**Pull request by KrzysiekJ**

### CODE REVIEW

**Comment by seriyps** [comment]
Please also add it to typespec https://github.com/epgsql/epgsql/blob/master/src/epgsql.erl#L43

**Comment by KrzysiekJ** [comment]
Thanks, I’ve added it.

**Comment by davidw** [comment]
Normally I would ask that you make pull requests against devel...

**Comment by KrzysiekJ** [comment]
Ok, I’m therefore closing this pull request in favor of #70.

**Pull request closed without merging**
