### PR TITLE
Fixed of error about empty queue

### PR DESCRIPTION
**Pull request by habibutsu**
Fixed of error about empty queue in case when remote connection was closed by server

Related issues: https://github.com/epgsql/epgsql/pull/62, https://github.com/epgsql/epgsql/pull/67, https://github.com/epgsql/epgsql/pull/79

### CODE REVIEW

**Comment by davidw** [comment]
Any idea why the tests are failing? I wonder if this fix helps: https://github.com/epgsql/epgsql/pull/90

**Comment by seriyps** [comment]
@davidw yep, exactly. I'm not sure, but I think it's possile to restart build somewhere in travis iterface.

**Comment by seriyps** [comment]
@davidw so, now all checks passed

**Comment by davidw** [comment]
Thanks, guys!

**Pull request merged**
