### PR TITLE
Unexpected crash report

### PR DESCRIPTION
**Pull request by habibutsu**
Unexpected crash report when unable to connect to server or connection closed by server

### CODE REVIEW

**Comment by davidw** [comment]
Hi,

You're saying that you expected the code to not crash if it could not connect?

**Comment by habibutsu** [comment]
Error code is returned and then handled properly in my code with logging and retries, but in log appear additional crash reports from epgsql.

**Comment by tnt-dev** [comment]
:+1: for this

**Comment by davidw** [comment]
@habibutsu sorry to be a bit slow, but I'm kind of busy these days.  Could you explain in further detail what the code currently does, and how your modification improves it?  Maybe a test case or two for the test suite would help.  Also, please develop against the devel branch.  Thank you!

**Comment by zxq9** [comment]
I'm not sure what the goal is supposed to be. ...? A connection attempt spawns a process to handle the socket, it crashes on failure (any failure), the crash is accurately reported, and the caller carries on from there. I don't see that the crash is "unexpected" or should be dealt with in the socket code. The only thing about the code I dislike is the case statement, actually -- and that's really a matter of opinion within a teeny tiny corner case.

**Comment by habibutsu** [comment]
### At first

As you known, error report is issued when reason of termination is different from
_normal_, _shutdown_ or _{shutdown,Term}_ (see [docs](https://github.com/erlang/otp/blob/OTP-17.5.5/lib/stdlib/doc/src/gen_server.xml#L580)). In common cases this is ok, but because the standard error logging in erlang is very restricted it seems to me that this is not very good. I would like to doing handling of error code myself in my code with logging if it is needed. Right now I get a duplicate of one of the same message.

At current moment we have following behaviour:
```erlang
1> epgsql:connect("127.0.0.1", "dbuser", "dbpassword", [{database, "testdb"}]).
** exception exit: econnrefused

=ERROR REPORT==== 9-Sep-2015::14:39:07 ===
** Generic server <0.33.0> terminating 
** Last message in was {connect,"127.0.0.1","dbuser","dbpassword",
                                [{database,"testdb"}]}
** When Server state == {state,undefined,undefined,<<>>,undefined,undefined,
                               undefined,
                               {[],[]},
                               undefined,[],[],[],[],[],[],undefined,
                               undefined}
** Reason for termination == 
** econnrefused
```

When i expected the following (in accordance with [spec](https://github.com/epgsql/epgsql/blob/3.1.0/src/epgsql.erl#L86)):

```erlang
1> epgsql:connect("127.0.0.1", "dbuser", "dbpassword", [{database, "testdb"}]).
{error,econnrefused}
```

### At second
In case when server stopped after connection you will get following behaviour with unexpected exception

```erlang
1> epgsql:connect("127.0.0.1", "dbuser", "dbpassword", [{database, "testdb"}]).
{ok,<0.33.0>}
2> % now db-server will be stopped
=ERROR REPORT==== 9-Sep-2015::14:45:52 ===
** Generic server <0.33.0> terminating 
** Last message in was {tcp,#Port<0.1722>,
                            <<69,0,0,0,109,83,70,65,84,65,76,0,67,53,55,80,48,
                              49,0,77,116,101,114,109,105,110,97,116,105,110,
                              103,32,99,111,110,110,101,99,116,105,111,110,32,
                              100,117,101,32,116,111,32,97,100,109,105,110,
                              105,115,116,114,97,116,111,114,32,99,111,109,
                              109,97,110,100,0,70,112,111,115,116,103,114,101,
                              115,46,99,0,76,50,56,55,53,0,82,80,114,111,99,
                              101,115,115,73,110,116,101,114,114,117,112,116,
                              115,0,0>>}
** When Server state == {state,gen_tcp,#Port<0.1722>,<<>>,
                               {16727,924265669},
                               on_message,
                               {codec,[],[]},
                               {[],[]},
                               undefined,
                               [{<<"application_name">>,<<>>},
                                {<<"client_encoding">>,<<"UTF8">>},
                                {<<"DateStyle">>,<<"ISO, MDY">>},
                                {<<"integer_datetimes">>,<<"on">>},
                                {<<"IntervalStyle">>,<<"postgres">>},
                                {<<"is_superuser">>,<<"off">>},
                                {<<"server_encoding">>,<<"UTF8">>},
                                {<<"server_version">>,<<"9.3.9">>},
                                {<<"session_authorization">>,<<"dbuser">>},
                                {<<"standard_conforming_strings">>,<<"on">>},
                                {<<"TimeZone">>,<<"Europe/Minsk">>}],
                               [],[],[],[],[],undefined,73}
** Reason for termination == 
** {empty,[{queue,get,[{[],[]}],[{file,"queue.erl"},{line,182}]},
           {epgsql_sock,command_tag,1,
                        [{file,"src/epgsql_sock.erl"},{line,405}]},
           {epgsql_sock,on_message,2,
                        [{file,"src/epgsql_sock.erl"},{line,680}]},
           {epgsql_sock,loop,1,[{file,"src/epgsql_sock.erl"},{line,330}]},
           {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},
           {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},
           {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
** exception error: empty
     in function  queue:get/1
        called as queue:get({[],[]})
     in call from epgsql_sock:command_tag/1 (src/epgsql_sock.erl, line 405)
     in call from epgsql_sock:on_message/2 (src/epgsql_sock.erl, line 680)
     in call from epgsql_sock:loop/1 (src/epgsql_sock.erl, line 330)
     in call from gen_server:try_dispatch/4 (gen_server.erl, line 593)
     in call from gen_server:handle_msg/5 (gen_server.erl, line 659)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 237)
```
instead of this (for example):
```erlang
** exception error: {shutdown,{error,fatal,<<"57P01">>,
                                     <<"terminating connection due to administrator command">>,
                                     []}}
```

**Comment by habibutsu** [comment]
Also I just now noticed that exists issue with the same problem that i described in second part of my comment above - _Handling remote connection close #67_

**Comment by ostinelli** [comment]
+1

**Comment by davidw** [comment]
In any event, this should be against the devel branch, not master.

**Comment by ostinelli** [comment]
Any news regarding this?

**Comment by davidw** [comment]
@ostinelli waiting for someone to make the pull request against the devel branch.  Unfortunately, I don't work with Erlang these days, so the project mostly depends on other people's contributions.

**Comment by habibutsu** [comment]
Sorry, I had a busy in last month, I am going to make new pull-request in a few days,  taking into account comments.

**Comment by davidw** [comment]
@habibutsu cool, thanks!

**Comment by habibutsu** [comment]
I made new pull-request - https://github.com/epgsql/epgsql/pull/89 and close this

**Pull request closed without merging**
