### PR TITLE
Support blessed `format_status/1` callback 

### PR DESCRIPTION
**Pull request by keynslug**
Add testcase on correctly redacted state.
Also mention that `format_status/2` callback is deprecated since OTP-25.

### CODE REVIEW

**Comment by seriyps** [comment]
Hi. In #276 the CI have been reworked a bit. May your PR wait for it to be merged and then rebased?

**Comment by keynslug** [comment]
Sure. Rebased it.

**Review by seriyps — APPROVED** [review]
Thanks!

**Review by davidw — APPROVED** [review]

**Comment by seriyps** [comment]
Thanks @keynslug and @davidw !

**Pull request merged**
