### PR TITLE
Use ubuntu trusty for OTP 18 on Travis

### PR DESCRIPTION
**Pull request by larshesel**

### CODE REVIEW

**Comment by seriyps** [comment]
Thanks!

**Comment by larshesel** [comment]
I just noticed that this PR went to master instead of `devel` - sorry about that - the right target should be `devel`, right?

**Comment by seriyps** [comment]
Ouch.. yep... would you mind creating one more pr to devel?

**Comment by larshesel** [comment]
New one in #201.

**Pull request merged**
