### PR TITLE
Add OTP-24 to CI

### PR DESCRIPTION
**Pull request by seriyps**

### CODE REVIEW

**Comment by seriyps** [comment]
Ok, seems OTP-24 is not available on Travis yet and there are some issues with OTP-18 as well.

I think it's ok to remove OTP-18, but for OTP-24... Maybe it's time to migrate to GitHub actions?

**Comment by seriyps** [comment]
Ok, I managed to fix OTP-18 in CI. But the lack of OTP-24 is kind of blocker. I think I'll try to port our CI to GitHub actions, but I'll most likely would need your help @davidw, because I don't have access to repository settings to enable it.

**Comment by ehamberg** [comment]
Looks like OTP 24 (at least 24.0.1 and 24.0.2) is available now (based on my reading of https://travis-ci.com/github/travis-ci/travis-erlang-builder/jobs/512328751).

**Comment by seriyps** [comment]
Yeah, but it seems Travis stopped to run opensource builds completely... Guess we really have to migrate to Github actions now.

**Comment by ehamberg** [comment]
Oh. Right. The cryptocurrency miners ruined that for everyone. :(

**Comment by seriyps** [comment]
Closing in favor of #262

**Pull request closed without merging**
