### PR TITLE
Support unlocalized severity (V) error field, added in PostgreSQL 9.6

### PR DESCRIPTION
**Pull request by ElectronicRU**
Closes issue #116.

### CODE REVIEW

**Comment by seriyps** [comment]
Can you, please, rebase this pull-request to `devel` branch? https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by ElectronicRU** [comment]
Done. Whew, that wiki is sure wordy for git rebase --onto ;)

**Comment by seriyps** [comment]
For me looks good.

**Comment by seriyps** [comment]
Thanks!

**Pull request merged**
