### PR TITLE
support for postgresql json type

### PR DESCRIPTION
**Pull request by talentdeficit**
support for the `json` type in postgres 9.2+

### CODE REVIEW

**Comment by seriyps** [comment]
Looks good. But you should rebase your PR over 'devel' branch, since 'master' is for stable releases.

**Comment by talentdeficit** [comment]
should i close this and reopen it against devel once rebased?

**Comment by davidw** [comment]
Whatever is easier for you.

**Comment by talentdeficit** [comment]
i've rebased this on `devel`

**Comment by WernerBuchert** [comment]
Are there plans to support the new jsonb type?

**Comment by davidw** [comment]
On github, it still says 'talentdeficit  wants to merge 4 commits into epgsql:master from talentdeficit:json'

**Comment by seriyps** [comment]
@davidw may we merge this? Because now epgsql still have no json type support.

**Pull request closed without merging**
