### PR TITLE
Add information to app file for hex package manager

### PR DESCRIPTION
**Pull request by jcomellas**
I've added information that is displayed in the hex.pm page for the package to the .app.src file.

### CODE REVIEW

**Comment by jcomellas** [comment]
Please let me know if there are any extra maintainers or if the license I set (BSD) is incorrect.

**Comment by davidw** [comment]
Let's just put 'epgsql team' - does that work?  It's not really fair to put my name when I didn't create the project or contribute the most code: https://github.com/epgsql/epgsql/graphs/contributors

**Comment by davidw** [comment]
Normally, pull requests should be against the `devel` branch, but in this case, since you're packaging up the `master` branch, it makes sense to have it here.

**Comment by jcomellas** [comment]
I've removed the maintainers line from the .app.src file.

**Comment by davidw** [comment]
Thanks!

**Comment by seriyps** [comment]
@jcomellas for some reason list of maintainers of epgsql app on hex.pm is 'null':

```
$ curl https://hex.pm/api/packages/epgsql | python -m json.tool                                                                                                                                  {
    "downloads": {
        "all": 1214,
        "day": 18,
        "week": 160
    },
    "inserted_at": "2015-10-22T17:58:15.612591Z",
    "meta": {
        "contributors": null,
        "description": "PostgreSQL Client",
        "licenses": [
            "BSD"
        ],
        "links": {
            "Github": "https://github.com/epgsql/epgsql"
        },
        "maintainers": null
    },
    "name": "epgsql",
    "releases": [
        {
            "inserted_at": "2015-10-30T20:52:05.858899Z",
            "updated_at": "2015-10-30T20:52:05.858912Z",
            "url": "https://hex.pm/api/packages/epgsql/releases/3.1.1",
            "version": "3.1.1"
        },
        {
            "inserted_at": "2015-10-22T17:58:15.631604Z",
            "updated_at": "2015-10-22T17:58:15.631613Z",
            "url": "https://hex.pm/api/packages/epgsql/releases/3.1.0",
            "version": "3.1.0"
        }
    ],
    "updated_at": "2015-10-30T20:52:05.845893Z",
    "url": "https://hex.pm/packages/epgsql"
}
```

because of that I can't see package info

```
$ DEBUG=1 rebar3 hex info epgsql                                                                                                                                                                 [0:26:56]
===> Load global config file /*****/.config/rebar3/rebar.config
===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{hex,info}]
epgsql
  Releases: 3.1.1, 3.1.0
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: function_clause
===> Stack trace to the error location: [{rebar3_hex_info,
                                                 '-join/1-lc$^0/1-0-',
                                                 [nil],
                                                 [{file,
                                                   "/*******/.cache/rebar3/plugins/rebar3_hex/src/rebar3_hex_info.erl"},
                                                  {line,184}]},
```

and can't publish new release

```
$ rebar3 hex publish
===> Verifying dependencies...
Publishing epgsql 3.2.0
  Dependencies:
    
  Excluded dependencies (not part of the Hex package):
    
  Included files:
<...>
Before publishing, please read Hex CoC: https://hex.pm/docs/codeofconduct
Proceed? ("Y")> 
===> Status Code: Forbidden (403)
Hex Error: account not authorized for this action

```
May you, please, fix this somehow?

**Comment by jcomellas** [comment]
@davidw This happened because I had removed the `maintainers` line after you told me it shouldn't be only you. I can create a pull request adding that and publish a new version. I'll set it to **epgsql team**. What email address should I put there?

**Comment by seriyps** [comment]
@jcomellas ahh.. Documentation on hex.pm is so sparse...
It looks like you may just add me to project owners in hex.pm like

```
rebar3 hex owner add epgsql me(at)seriyps.ru
# of course @ instead of (at)
```

Or I can ping you each time when new release will be tagged.

And 'maintainers' field is not related to access rules - it's just informative. I'll add this 'maintainers', 'license' etc tags, but with next git tag.
And it looks like it's not possible to add permissions to whole *epgsql team*. Only one-by-one.

**Comment by jcomellas** [comment]
@davidw I get a failure from rebar3 when I try to add you as an owner. It's pretty late here. I'll try again tomorrow.

**Comment by davidw** [comment]
@jcomellas please add both @seriyps and myself when you get a chance.  Thank you!

**Comment by seriyps** [comment]
@jcomellas any progress?

**Comment by jcomellas** [comment]
@davidw, @seriyps: Sorry, for the delay. I continued having issues with rebar3 when trying to publish to hex.pm. It turns out that I had an old version of the `rebar3_hex` plugin on my computer that rebar3 was apparently not updating automatically.

Anyway, I managed to publish version 3.2.0 and add @seriyps as owner. I tried adding @davidw as owner too but it failed when using the email present in his GitHub page. The error I was getting is:
```
===> Unable to remove package "epgsql", <<131,116,0,0,0,2,109,0,0,0,
                                                     7,109,101,115,115,97,103,
                                                     101,109,0,0,0,14,80,97,
                                                     103,101,32,110,111,116,32,
                                                     102,111,117,110,100,109,0,
                                                     0,0,6,115,116,97,116,117,
                                                     115,98,0,0,1,148>> (404)
```

**Comment by seriyps** [comment]
@jcomellas maybe @davidw has no hex.pm account?

**Comment by davidw** [comment]
I'm almost sure I don't.

**Comment by seriyps** [comment]
@jcomellas thanks! I'm in epgsql owners list now.
@davidw In this case you should create an a hex.pm account in order to be added as epgsql owner in hex (and to get 'publish' permissions)
https://www.rebar3.org/docs/hex-package-management#section-registers-a-new-user, it's an interactive command.

**Pull request merged**
