### PR TITLE
Fix epgsqla and epgsqli API specs

### PR DESCRIPTION
**Pull request by zmstone**

### CODE REVIEW

**Comment by seriyps** [comment]
Hi. We usualy do PRs over `devel` branch. devel branch merged it to master from time to time and then new tag / version added. But since your PR is small enough I think we can accept it like it is.

**Comment by seriyps** [comment]
Would you mind to fix all the specs in epgsql, epgsqla, epgsqli where SQL query is an argument?

**Comment by seriyps** [comment]
So yeah, can you, please, do the same with `epgsqli` module?

**Comment by zmstone** [comment]
done.

**Comment by seriyps** [comment]
Thanks!

**Pull request merged**
