### PR TITLE
Fix for Erlang/OTP 20.0

### PR DESCRIPTION
**Pull request by okeuday**
Avoid conflict with new floor function.

### CODE REVIEW

**Comment by davidw** [comment]
Hi, could you do this one against the 'devel' branch?  We should probably then release soonish to be ready for 20.0.  It'd be kind of nice if it could optionally use the OTP version of floor, too.

**Comment by okeuday** [comment]
Won't be able to get time to do that.

**Comment by davidw** [comment]
@seriyps have a look?

**Comment by seriyps** [comment]
@davidw looks good

**Comment by davidw** [comment]
Still like to conditionally use the native floor for 20 and hacked up an ugly version of it.

```
-ifndef(OTP_RELEASE).
flooring(X) ->
    T = erlang:trunc(X),
    case (X - T) of
        N when N < 0 -> T - 1;
        N when N > 0 -> T;
        _            -> T
    end.
-else.
-ifdef(?OTP_RELEASE >= 20).
flooring(X) ->
    floor(X).
-else.
flooring(X) ->
    T = erlang:trunc(X),
    case (X - T) of
        N when N < 0 -> T - 1;
        N when N > 0 -> T;
        _            -> T
    end.
-endif.
-endif.
```

But... yuck.

**Comment by seriyps** [comment]
@davidw also smth like `erlang:function_exported(erlang, crc32, 1)` but I'm not sure if it's more effective.

**Pull request merged**
