### PR TITLE
Array of record type support

### PR DESCRIPTION
**Pull request by egobrain**

### CODE REVIEW

**Comment by egobrain** [comment]
Is this project alive?
When it can be merged (or declined) ?

**Comment by davidw** [comment]
@egobrain sorry, I moved across the world and have a different job that's, unfortunately, not an Erlang job, so I've been a bit remiss in keeping after these changes.  This looks good, though; any objections @seriyps ?

**Comment by seriyps** [comment]
@davidw yep, looks good.

**Comment by davidw** [comment]
@egobrain @seriyps thanks!

**Comment by davidw** [comment]
Tests are failing, it seems https://travis-ci.org/epgsql/epgsql/builds/101926825

**Comment by seriyps** [comment]
But looks like the reason is not this pull-request.
For some reason travis tries to install and launch both postgresql 9.3 and 9.5

**Pull request merged**
