### PR TITLE
Fixing error in comments.

### PR DESCRIPTION
**Pull request by aherranz**
I think the documentation (and comments in code) are wrong. I have also added delete statement to the comments (with insert and update).

### CODE REVIEW

**Comment by seriyps** [comment]
Looks good.

**Comment by davidw** [comment]
Pull requests, as per the documentation, should be made against devel. Thanks!

**Comment by seriyps** [comment]
May you also, please, update the same comments in README?

**Comment by aherranz** [comment]
From devel (sorry), and README updated: #87

**Pull request closed without merging**
